#!/bin/sh
npm run lint -s
printf "\033[35mLinted\033[0m\n"
npm run prettify -s
printf "\033[35mPrettified\033[0m\n"
rm -f ./package-lock.json
cd server
rm -f ./package-lock.json
cd ../client
rm -f ./package-lock.json
cd ..
printf "\033[35mRemoved package-lock.json\033[0m\n"
git config --global core.autocrlf input
git add --all
git add --all
